sudo: required
language: python
services:
  - docker

# cache:
#   directories:
#   - $CACHE_DIR

# before_install:
#   - if [ -f ${CACHE_FILE_PYTHON} ]; then gunzip -c ${CACHE_FILE_PYTHON} | docker load; fi
#   - if [ -f ${CACHE_FILE_DYNAMODB} ]; then gunzip -c ${CACHE_FILE_DYNAMODB} | docker load; fi

# install:
#   - mkdir -p $CACHE_DIR
#   - if [ ! -f ${CACHE_FILE_PYTHON} ]; then docker save python:2.7.12 | gzip > ${CACHE_FILE_PYTHON}; fi
#   - if [ ! -f ${CACHE_FILE_DYNAMODB} ]; then docker save peopleperhour/dynamodb:latest | gzip > ${CACHE_FILE_DYNAMODB}; fi

# env:
#   global:
#     - CACHE_DIR=$HOME/.cache/docker
#     - CACHE_FILE_PYTHON=$CACHE_DIR/python.tar.gz
#     - CACHE_FILE_DYNAMODB=$CACHE_DIR/dynamodb.tar.gz

script:
  - docker-compose run app

deploy:
  - provider: pypi
    distributions: sdist
    user: "geeknam"
    password:
      secure: "Fy6mxAyBDy/6GC7v+AMfNJrxLq4nZ4w5fR0Gueldfd279bHEsTtgv+Q1tHH0JpOv9jbteGTdNKnxBfD5p/WavGsL1FTXYISjTPwoK0Y5MVY5Zj3qadtdGRpophsiCcp52ZPcJtP1DadwLuUivaAQrJP1eDALrejSY5lOf9Qw2dBzDsLAvzI1JoCfqhOaIGNIORl6yjUw5qfaCuQ/WDtzwsuIP8idK/+KMz3PN/kLzUwoihALnd+e/kZ0VPqnkeXiLj0DtsL5+jyF38ow3QZKv0TVi/7dLLwHNewSbRjfrSTq1KeTEnZKKlD5P/zgeylrG51NZzHzF0s4w1E2XlDQo9sf1gIF192Clzpe7sasZPmB+d5KT5x+O6gNO2jTwWmup5C40+1D4bgPEAf7X5Ej2Hd8SIydxJcTX3C6kTEiBTEuKPkzF3R/r8/WcqyzPwzTF0D1GjqtCt8uXWttQr0jR7A+BPCwBdUaWvh0EYNxvAcE9gKeLUfQxJF+ahVVu2w32S5zM7te2Nr0+tUDgWQNo7YhcVtdso7PYZpLaTkEKhuXhh1xhYV6LOog+8RR2gwC5n+t2ACqZxI6697NMrmOBNIS+ophSzqz7iEVa4XmdFCZ3EG/7pcMc8LGfK4qlsDwB1L6V2nzWZyj3BFHyWB690uhQ3ZdJaNA8DEZCJQ2wNo="
    on:
      branch: master
      tags: true

addons:
  code_climate:
    repo_token: c8d563dc62945055087c7099e1a6383949c5b4b39ab6319406e0bc3139ba8acf

notifications:
  slack:
    secure: oLOQhMeFPMPtkslGYnvzIAhuzgPU7IsAkK2dxGeLUqKZI/GACZtEBlgk3CUS6ibXYOmkwcvbBp3JS4AYZooubyqemqiQa3bA17ScFOSqUWj5A7QKuWiGFjVtO4MQJisda//6OA6igfiU8VRP0G0NYILZnNbiScEIk45ivSaposqDkvMZS/pup9saJiQ2WySgdzJ6QtlDv+VISo/avIneh5PLMUSBV4m/T07vD6sYsEgLx7bwXIHHR0Xu3tgLCqA0jXXJXM3EbIoVZTSTF1eai6VlTAd5EbgNMkx7C14iUvwlYqHATTsXaY8INTyGIiJElQOgnAUbjyzHvUhlGTpd8VZ1EBZslnLxQB5Bo9c2cTHfwLSNWrnnM/gXvfBjzy1ti1IN/uLpVbIFABki3/b3sRrcpgobOIeKnupPQR3oSERLnCBYRvbaNVBoXfVG9C1g7roR5U4ibcNprEgMKTiUeWl1W16q8a5srIJ6mLJEU4ub4wdD+3HxTlpH+GC2crt0swV++9H5zSyfmuhGf2w3q+ZafT+vjK/plJ4MGsGWlcU+YJ0DW2Iebq5RYn/F3PO0DP4tGOGhiBpYeY4Tke+ylbYtIleD1koBs2vVLPzSqB8Cdklyhy48FmWM6eJ6RyKW33DvUjRynyYr/tan0I1mIeGON49QI0kx3s/+70aYbW0=
