version: '2'
services:
  dynamodb:
    image: peopleperhour/dynamodb
  app:
    build: .
    working_dir: /code
    command: bash runtest.sh
    depends_on:
      - dynamodb
    volumes:
      - .:/code
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      PYTHONPATH: /code
      DYNAMODB_HOST: http://dynamodb:8000
      CODECLIMATE_REPO_TOKEN: ${CODECLIMATE_REPO_TOKEN}
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      GH_TOKEN: ${GH_TOKEN}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_PULL_REQUEST: ${TRAVIS_PULL_REQUEST}
      TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}
      TRAVIS_TAG: ${TRAVIS_TAG}
