version: '2'
services:
  dynamodb:
    image: peopleperhour/dynamodb
  app:
    build: .
    working_dir: /code
    command: bash runtest.sh
    depends_on:
      - dynamodb
    volumes:
      - .:/code
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DYNAMODB_HOST: http://dynamodb:8000
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}