template_path: templates/dynamodb.yaml
parameters:
  TableName: !environment_variable EventTableName
  ReadCapacityUnits: 1
  WriteCapacityUnits: 1
  DynamoDBResourceNameExportName: DynamoDBEventTable
  DynamoDBStreamArnExportName: DynamoDBEventStreamArn